# server
server:
  port: 8080


# Spring
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bug_trackingdb
    username: appuser
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.MariaDB106Dialect
  mail:
    host: localhost
    port: 1025
    username: username
    password: password
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "mappings,health,info"


# token properties
app:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://localhost:3306/bug_trackingdb
    username: appuser
    password: password
    maximum-pool-size: 20
  token:
    access-token-header-name-sent-by-client: Authorization
    key: jAOa=kms)dLxgE#*($#Qe_XH!uPq8Vdby@YlnvkANox^u3dQ53YU%n4B
    access-token-life-time: 2592000000
    access-token-cookie-name: access-token
